#define TARGET_NAME "cvic20"
#define TARGET_DESC "Commodore VIC-20"
#define CPU65_TRAP_OPCODE 0xFC
#define CPU65 cpu65
#define CPU_6502_NMOS_ONLY

#define CONFIG_EMSCRIPTEN_OK

#define XEMU_CONFIGDB_SUPPORT
#define XEMU_OSD_SUPPORT
