#define TARGET_NAME "primo"
#define TARGET_DESC "Primo"
#define Z80EX_OPSTEP_FAST_AND_ROUGH
#define CONFIG_DROPFILE_CALLBACK
#define CONFIG_QUIT_CALLBACK
#define CONFIG_EMSCRIPTEN_OK
#define HAVE_XEMU_EXEC_API
