#define TARGET_NAME "primo"
#define TARGET_DESC "Primo"
#define Z80EX_OPSTEP_FAST_AND_ROUGH
#define CONFIG_DROPFILE_CALLBACK
#define CONFIG_QUIT_CALLBACK
#define CONFIG_EMSCRIPTEN_OK

#ifndef XEMU_ARCH_HTML
#define XEMU_USE_LODEPNG
#define XEMU_FILES_SCREENSHOT_SUPPORT
#define HAVE_XEMU_EXEC_API
#endif

#define XEMU_CONFIGDB_SUPPORT
