#define TARGET_NAME "recpm"
#define TARGET_DESC "ReCP/M"
#define Z80EX_OPSTEP_FAST_AND_ROUGH
#define CONFIG_KBD_ALSO_REPEATS
#define CONFIG_KBD_ALSO_RAW_SDL_CALLBACK
//#define CONFIG_KBD_ALSO_TEXTEDITING_SDL_CALLBACK
#define CONFIG_KBD_ALSO_TEXTINPUT_SDL_CALLBACK
//#define CONFIG_QUIT_CALLBACK
//#define CONFIG_EMSCRIPTEN_OK
