/* autogenerated from ./opcodes_ddfd.dat, do not edit */

/*ADD IY,BC*/
static void op_FD_0x09(void)
{
	ADD16(IY,BC);
	T_WAIT_UNTIL(11);
	return;
}

/*ADD IY,DE*/
static void op_FD_0x19(void)
{
	ADD16(IY,DE);
	T_WAIT_UNTIL(11);
	return;
}

/*LD IY,@*/
static void op_FD_0x21(void)
{
	temp_word.b.l=READ_OP();
	temp_word.b.h=READ_OP();
	LD16(IY,temp_word.w);
	T_WAIT_UNTIL(10);
	return;
}

/*LD (@),IY*/
static void op_FD_0x22(void)
{
	temp_addr.b.l=READ_OP();
	temp_addr.b.h=READ_OP();
	LD_RP_TO_ADDR_MPTR_16(temp_word.w,IY, temp_addr.w);
	WRITE_MEM(temp_addr.w,temp_word.b.l,10);
	WRITE_MEM(temp_addr.w+1,temp_word.b.h,13);
	T_WAIT_UNTIL(16);
	return;
}

/*INC IY*/
static void op_FD_0x23(void)
{
	INC16(IY);
	T_WAIT_UNTIL(6);
	return;
}

/*INC IYH*/
static void op_FD_0x24(void)
{
	INC(IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*DEC IYH*/
static void op_FD_0x25(void)
{
	DEC(IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYH,#*/
static void op_FD_0x26(void)
{
	temp_byte=READ_OP();
	LD(IYH,temp_byte);
	T_WAIT_UNTIL(7);
	return;
}

/*ADD IY,IY*/
static void op_FD_0x29(void)
{
	ADD16(IY,IY);
	T_WAIT_UNTIL(11);
	return;
}

/*LD IY,(@)*/
static void op_FD_0x2a(void)
{
	temp_addr.b.l=READ_OP();
	temp_addr.b.h=READ_OP();
	READ_MEM(temp_word.b.l,temp_addr.w,10);
	READ_MEM(temp_word.b.h,temp_addr.w+1,13);
	LD_RP_FROM_ADDR_MPTR_16(IY,temp_word.w, temp_addr.w);
	T_WAIT_UNTIL(16);
	return;
}

/*DEC IY*/
static void op_FD_0x2b(void)
{
	DEC16(IY);
	T_WAIT_UNTIL(6);
	return;
}

/*INC IYL*/
static void op_FD_0x2c(void)
{
	INC(IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*DEC IYL*/
static void op_FD_0x2d(void)
{
	DEC(IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYL,#*/
static void op_FD_0x2e(void)
{
	temp_byte=READ_OP();
	LD(IYL,temp_byte);
	T_WAIT_UNTIL(7);
	return;
}

/*INC (IY+$)*/
static void op_FD_0x34(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	INC(temp_byte);
	WRITE_MEM((IY+temp_byte_s),temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*DEC (IY+$)*/
static void op_FD_0x35(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	DEC(temp_byte);
	WRITE_MEM((IY+temp_byte_s),temp_byte,16);
	T_WAIT_UNTIL(19);
	return;
}

/*LD (IY+$),#*/
static void op_FD_0x36(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	temp_byte=READ_OP();
	LD(temp_byte,temp_byte);
	WRITE_MEM((IY+temp_byte_s),temp_byte,12);
	T_WAIT_UNTIL(15);
	return;
}

/*ADD IY,SP*/
static void op_FD_0x39(void)
{
	ADD16(IY,SP);
	T_WAIT_UNTIL(11);
	return;
}

/*LD B,IYH*/
static void op_FD_0x44(void)
{
	LD(B,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*LD B,IYL*/
static void op_FD_0x45(void)
{
	LD(B,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*LD B,(IY+$)*/
static void op_FD_0x46(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	LD(B,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*LD C,IYH*/
static void op_FD_0x4c(void)
{
	LD(C,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*LD C,IYL*/
static void op_FD_0x4d(void)
{
	LD(C,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*LD C,(IY+$)*/
static void op_FD_0x4e(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	LD(C,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*LD D,IYH*/
static void op_FD_0x54(void)
{
	LD(D,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*LD D,IYL*/
static void op_FD_0x55(void)
{
	LD(D,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*LD D,(IY+$)*/
static void op_FD_0x56(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	LD(D,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*LD E,IYH*/
static void op_FD_0x5c(void)
{
	LD(E,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*LD E,IYL*/
static void op_FD_0x5d(void)
{
	LD(E,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*LD E,(IY+$)*/
static void op_FD_0x5e(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	LD(E,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*LD IYH,B*/
static void op_FD_0x60(void)
{
	LD(IYH,B);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYH,C*/
static void op_FD_0x61(void)
{
	LD(IYH,C);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYH,D*/
static void op_FD_0x62(void)
{
	LD(IYH,D);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYH,E*/
static void op_FD_0x63(void)
{
	LD(IYH,E);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYH,IYH*/
static void op_FD_0x64(void)
{
	LD(IYH,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYH,IYL*/
static void op_FD_0x65(void)
{
	LD(IYH,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*LD H,(IY+$)*/
static void op_FD_0x66(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	LD(H,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*LD IYH,A*/
static void op_FD_0x67(void)
{
	LD(IYH,A);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYL,B*/
static void op_FD_0x68(void)
{
	LD(IYL,B);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYL,C*/
static void op_FD_0x69(void)
{
	LD(IYL,C);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYL,D*/
static void op_FD_0x6a(void)
{
	LD(IYL,D);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYL,E*/
static void op_FD_0x6b(void)
{
	LD(IYL,E);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYL,IYH*/
static void op_FD_0x6c(void)
{
	LD(IYL,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*LD IYL,IYL*/
static void op_FD_0x6d(void)
{
	LD(IYL,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*LD L,(IY+$)*/
static void op_FD_0x6e(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	LD(L,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*LD IYL,A*/
static void op_FD_0x6f(void)
{
	LD(IYL,A);
	T_WAIT_UNTIL(4);
	return;
}

/*LD (IY+$),B*/
static void op_FD_0x70(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	LD(temp_byte,B);
	WRITE_MEM((IY+temp_byte_s),temp_byte,12);
	T_WAIT_UNTIL(15);
	return;
}

/*LD (IY+$),C*/
static void op_FD_0x71(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	LD(temp_byte,C);
	WRITE_MEM((IY+temp_byte_s),temp_byte,12);
	T_WAIT_UNTIL(15);
	return;
}

/*LD (IY+$),D*/
static void op_FD_0x72(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	LD(temp_byte,D);
	WRITE_MEM((IY+temp_byte_s),temp_byte,12);
	T_WAIT_UNTIL(15);
	return;
}

/*LD (IY+$),E*/
static void op_FD_0x73(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	LD(temp_byte,E);
	WRITE_MEM((IY+temp_byte_s),temp_byte,12);
	T_WAIT_UNTIL(15);
	return;
}

/*LD (IY+$),H*/
static void op_FD_0x74(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	LD(temp_byte,H);
	WRITE_MEM((IY+temp_byte_s),temp_byte,12);
	T_WAIT_UNTIL(15);
	return;
}

/*LD (IY+$),L*/
static void op_FD_0x75(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	LD(temp_byte,L);
	WRITE_MEM((IY+temp_byte_s),temp_byte,12);
	T_WAIT_UNTIL(15);
	return;
}

/*LD (IY+$),A*/
static void op_FD_0x77(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	LD(temp_byte,A);
	WRITE_MEM((IY+temp_byte_s),temp_byte,12);
	T_WAIT_UNTIL(15);
	return;
}

/*LD A,IYH*/
static void op_FD_0x7c(void)
{
	LD(A,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*LD A,IYL*/
static void op_FD_0x7d(void)
{
	LD(A,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*LD A,(IY+$)*/
static void op_FD_0x7e(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	LD(A,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*ADD A,IYH*/
static void op_FD_0x84(void)
{
	ADD(A,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*ADD A,IYL*/
static void op_FD_0x85(void)
{
	ADD(A,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*ADD A,(IY+$)*/
static void op_FD_0x86(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	ADD(A,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*ADC A,IYH*/
static void op_FD_0x8c(void)
{
	ADC(A,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*ADC A,IYL*/
static void op_FD_0x8d(void)
{
	ADC(A,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*ADC A,(IY+$)*/
static void op_FD_0x8e(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	ADC(A,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*SUB IYH*/
static void op_FD_0x94(void)
{
	SUB(IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*SUB IYL*/
static void op_FD_0x95(void)
{
	SUB(IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*SUB (IY+$)*/
static void op_FD_0x96(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	SUB(temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*SBC A,IYH*/
static void op_FD_0x9c(void)
{
	SBC(A,IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*SBC A,IYL*/
static void op_FD_0x9d(void)
{
	SBC(A,IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*SBC A,(IY+$)*/
static void op_FD_0x9e(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	SBC(A,temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*AND IYH*/
static void op_FD_0xa4(void)
{
	AND(IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*AND IYL*/
static void op_FD_0xa5(void)
{
	AND(IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*AND (IY+$)*/
static void op_FD_0xa6(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	AND(temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*XOR IYH*/
static void op_FD_0xac(void)
{
	XOR(IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*XOR IYL*/
static void op_FD_0xad(void)
{
	XOR(IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*XOR (IY+$)*/
static void op_FD_0xae(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	XOR(temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*OR IYH*/
static void op_FD_0xb4(void)
{
	OR(IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*OR IYL*/
static void op_FD_0xb5(void)
{
	OR(IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*OR (IY+$)*/
static void op_FD_0xb6(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	OR(temp_byte);
	T_WAIT_UNTIL(15);
	return;
}

/*CP IYH*/
static void op_FD_0xbc(void)
{
	CP(IYH);
	T_WAIT_UNTIL(4);
	return;
}

/*CP IYL*/
static void op_FD_0xbd(void)
{
	CP(IYL);
	T_WAIT_UNTIL(4);
	return;
}

/*CP (IY+$)*/
static void op_FD_0xbe(void)
{
	temp_byte=READ_OP();
	temp_byte_s=(temp_byte & 0x80)? -(((~temp_byte) & 0x7f)+1): temp_byte;
	MEMPTR=(IY+temp_byte_s);
	READ_MEM(temp_byte,(IY+temp_byte_s),12);
	CP(temp_byte);
	T_WAIT_UNTIL(15);
	return;
}


/*POP IY*/
static void op_FD_0xe1(void)
{
	POP(IY, /*rd*/4,7);
	T_WAIT_UNTIL(10);
	return;
}

/*EX (SP),IY*/
static void op_FD_0xe3(void)
{
	READ_MEM(temp_word.b.l,(SP),4);
	READ_MEM(temp_word.b.h,(SP+1),7);
	EX_MPTR(temp_word.w,IY);
	WRITE_MEM((SP),temp_word.b.l,11);
	WRITE_MEM((SP+1),temp_word.b.h,14);
	T_WAIT_UNTIL(19);
	return;
}

/*PUSH IY*/
static void op_FD_0xe5(void)
{
	PUSH(IY, /*wr*/5,8);
	T_WAIT_UNTIL(11);
	return;
}

/*JP IY*/
static void op_FD_0xe9(void)
{
	JP_NO_MPTR(IY);
	T_WAIT_UNTIL(4);
	return;
}

/*LD SP,IY*/
static void op_FD_0xf9(void)
{
	LD16(SP,IY);
	T_WAIT_UNTIL(6);
	return;
}



/**/
static const z80ex_opcode_fn opcodes_fd[0x100] = {
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_FD_0x09    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_FD_0x19    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_FD_0x21    , op_FD_0x22    , op_FD_0x23    ,
 op_FD_0x24    , op_FD_0x25    , op_FD_0x26    , NULL          ,
 NULL          , op_FD_0x29    , op_FD_0x2a    , op_FD_0x2b    ,
 op_FD_0x2c    , op_FD_0x2d    , op_FD_0x2e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x34    , op_FD_0x35    , op_FD_0x36    , NULL          ,
 NULL          , op_FD_0x39    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x44    , op_FD_0x45    , op_FD_0x46    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x4c    , op_FD_0x4d    , op_FD_0x4e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x54    , op_FD_0x55    , op_FD_0x56    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x5c    , op_FD_0x5d    , op_FD_0x5e    , NULL          ,
 op_FD_0x60    , op_FD_0x61    , op_FD_0x62    , op_FD_0x63    ,
 op_FD_0x64    , op_FD_0x65    , op_FD_0x66    , op_FD_0x67    ,
 op_FD_0x68    , op_FD_0x69    , op_FD_0x6a    , op_FD_0x6b    ,
 op_FD_0x6c    , op_FD_0x6d    , op_FD_0x6e    , op_FD_0x6f    ,
 op_FD_0x70    , op_FD_0x71    , op_FD_0x72    , op_FD_0x73    ,
 op_FD_0x74    , op_FD_0x75    , NULL          , op_FD_0x77    ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x7c    , op_FD_0x7d    , op_FD_0x7e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x84    , op_FD_0x85    , op_FD_0x86    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x8c    , op_FD_0x8d    , op_FD_0x8e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x94    , op_FD_0x95    , op_FD_0x96    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0x9c    , op_FD_0x9d    , op_FD_0x9e    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0xa4    , op_FD_0xa5    , op_FD_0xa6    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0xac    , op_FD_0xad    , op_FD_0xae    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0xb4    , op_FD_0xb5    , op_FD_0xb6    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 op_FD_0xbc    , op_FD_0xbd    , op_FD_0xbe    , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_FD_0xe1    , NULL          , op_FD_0xe3    ,
 NULL          , op_FD_0xe5    , NULL          , NULL          ,
 NULL          , op_FD_0xe9    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          ,
 NULL          , op_FD_0xf9    , NULL          , NULL          ,
 NULL          , NULL          , NULL          , NULL          
};
