#define TARGET_NAME "cx16"
#define TARGET_DESC "Commander X16"
//#define CPU65_TRAP_OPCODE 0xFC
#define CPU65 cpu65
#define CPU65_NO_RMW_EMULATION

#define CONFIG_KBD_ALSO_REPEATS

//#define DEBUG_CPU

#define CONFIG_EMSCRIPTEN_OK
