#define TARGET_NAME "pc"
#define TARGET_DESC "PC"
#define Z80EX_OPSTEP_FAST_AND_ROUGH
#define CONFIG_DROPFILE_CALLBACK
#define CONFIG_QUIT_CALLBACK
#define CONFIG_EMSCRIPTEN_OK
#define HAVE_XEMU_EXEC_API
#define XEMU_CONFIGDB_SUPPORT
#define XEMU_OSD_SUPPORT
#define XEMU_VGA_FONT_8X16
