#define TARGET_NAME "tvc"
#define TARGET_DESC "Videoton TV Computer"
#define Z80EX_OPSTEP_FAST_AND_ROUGH
#define CONFIG_SDEXT_SUPPORT

#define CONFIG_EMSCRIPTEN_OK
#define XEMU_CONFIGDB_SUPPORT
#define XEMU_OSD_SUPPORT
