#define TARGET_NAME "ep128"
#define TARGET_DESC "Enterprise 128"
#define CONFIG_Z180

#ifdef CONFIG_Z180
#define Z80EX_Z180_SUPPORT
#endif

#define Z80EX_ED_TRAPPING_SUPPORT
#define Z80EX_CALLBACK_PROTOTYPE extern
#define CONFIG_SDEXT_SUPPORT

#if defined(XEMU_ARCH_HTML) || defined(XEMU_ARCH_ANDROID)
#define NO_CONSOLE
#endif

#ifndef XEMU_ARCH_HTML
#define XEMU_USE_LODEPNG
#define XEMU_FILES_SCREENSHOT_SUPPORT
#define HAVE_XEMU_EXEC_API
#endif

#define CONFIG_EMSCRIPTEN_OK
#define CONFIG_ANDROID_OK

#define VARALIGN MAXALIGNED

#define XEMU_CONFIGDB_SUPPORT
#define XEMU_OSD_SUPPORT
